### PR TITLE
Feature UCL

### PR DESCRIPTION
**Pull request by sgerbino**
This is a drop in replacement implementation for configuration file parsing using libucl.

### CODE REVIEW

**Comment by sgerbino** [comment]
Build is failing because the CI server doesn't have libucl installed.

**Comment by sgerbino** [comment]
Looks like we need a way of getting a stable release of libucl on your debian CI server

**Comment by mheily** [comment]
I have created a new branch called mheily-feature-ucl to work on this. It is not fully functional yet.

**Comment by mheily** [comment]
I found a problem with manifest_rectify(). It is missing some
transformations that the old code did; for example the special handling of
Program and ProgramArguments.

I've started writing some unit tests to check the expected behavior and
would like to run them against your branch soon

Looks like we need a way of getting a stable release of libucl on your
debian CI server

**Comment by mheily** [comment]
This has been cherry-picked into the master branch, along with some changes for testing.

**Pull request closed without merging**
